### ISSUE TITLE
Rsq/info scores of meta imputation

### ISSUE THREAD

**Issue by yaacoo** [Santy-8128/MetaMinimac#2]
It seems that metaMinimac does not generate Rsq / info file.
Is there a way to turn on this option? Can I calculate them based from the original dosage files that contain the allele frequency?

**Comment by yukt** [comment]
This feature is available in the rsq branch.
Or you can calculate them using this equation r2=Var(HDS)/(p(1-p)), where p=Mean(HDS)

**Comment by yaacoo** [comment]
thanks, i'll try the rsq brach first
