### ISSUE TITLE
giving more weight to one imputed dataset

### ISSUE THREAD

**Issue by yaacoo** [Santy-8128/MetaMinimac#3]
I am using MetaMinimac to merge the imputation results to 2 reference panels- the HRC and a cohort specific panel one that consists of ~3K individuals. 
Since the HRC is ~30K individuals, I would like to give more weight to the HRC imputation results. 

Can I give more weight to the bigger, better, imputation panel?

**Comment by yukt** [comment]
Sorry, this feature is not supported in MetaMinimac.

**Comment by yaacoo** [comment]
thanks
